### ISSUE TITLE
Support for Bar/Line combo charts

### ISSUE THREAD

**Issue by MCvdBank** [mattosaurus/ChartJSCore#16]
Hi,
I'm trying to configure a bar/line combo chart with your library, but it seems as if this is not fully supported.
In my case, I created a chart of type bar, and added a `BarDataset` object to it for my primary dataset which renders fine. I then added a `LineDataset` to the chart, but it is then also drawn as a bar chart.

```
Chart chart = new Chart();
chart.Type = "bar";
Data data = new Data();
data.Datasets = new List<Dataset>();

// Add bar dataset
data.Datasets.Add(new BarDataset
{
	Data = new List<double>()
});
// Add line dataset
data.Datasets.Add(new LineDataset
{
	Data = new List<double>()
});
```

Comparing the JS generated from your library to that of the example provided in the [ChartJS documentation](http://www.chartjs.org/samples/latest/charts/combo-bar-line.html), it seems as if a simple `type` property is missing from the dataset JSON. If I manually add `"type":"line"` to the line's dataset output, it works. 

My suggestion would be to add a private string property to your `BarDataset` and `LineDataset` models, which should then be included in the generated JS output.

```
namespace ChartJSCore.Models
{
	public class LineDataset : Dataset
	{
		/// <summary>
		/// The type of the dataset
		/// </summary>
		private string Type = "line";
	}
	
	public class BarDataset : Dataset
	{
		/// <summary>
		/// The type of the dataset
		/// </summary>
		private string Type = "bar";
	}
}
```

It would be greatly appreciated it you could look into this. Thanks.

**Comment by mattosaurus** [comment]
Hi @MCvdBank, this looks easy enough to implement, feel free to submit a pull request if you're happy making the changes yourself or I'll do it myself when I get a chance in the next couple of days.
