### ISSUE TITLE
Support for data point labeling

### ISSUE THREAD

**Issue by MCvdBank** [mattosaurus/ChartJSCore#17]
Hi,
Is there a possibility that you would consider adding support for data point labeling as illustrated in one of the ChartJS examples [here](http://www.chartjs.org/samples/latest/advanced/data-labelling.html)?

The trick seems to be to define a plugin using the `afterDatasetsDraw` event, and manually drawing a label on the canvas for each data point. However, instead of defining a global plugin as per the example, I would rather define the plugin for each individual chart, as documented [here](http://www.chartjs.org/docs/latest/developers/plugins.html).

Thank you for your consideration.

**Comment by mattosaurus** [comment]
Hi @MCvdBank, global plugins probably wouldn't work very well with this project but I should be able to add a plugin field into which you can add your own custom javascript.

**Comment by MCvdBank** [comment]
Awesome! Thanks.

**Comment by mattosaurus** [comment]
Hi @MCvdBank, I've made this and your other suggested change and published v1.2.4 of the NuGet package.

**Comment by MCvdBank** [comment]
Thanks @mattosaurus. This works perfectly, and opens up a lot of functionality.
