### ISSUE TITLE
Plugin support at the dataset level

### ISSUE THREAD

**Issue by djcarter85** [mattosaurus/ChartJSCore#19]
I'm using the chartjs-plugins-datalabels plugin to add data labels to my chart. In order to do this I have had to create custom classes which inherit from the standard ChartJSCore classes, because I need `plugins.datalabels` underneath `chart.options` and also `datalabels` underneath `chart.data.datasets`.

Is there a way of adding support for plugins like this without having to add custom classes?

**Comment by mattosaurus** [comment]
Hi @djcarter85, plugin support is certainly something I'd like to improve in this project, though given how varied they are I'm not sure of the best way to do this. For plugins that require additional fields on the standard classes creating new child classes with the required fields sounds like the best option though if you (or anyone else) can think of a better solution I'd be happy to implement it.

**Comment by djcarter85** [comment]
That's the difficult thing about this: JavaScript objects allow plugins really easily because you can add properties to an object, whereas the whole point of ChartJSCore is to pre-define the classes.

I'm not sure the easiest way to do this (I don't have much experience with JSON serialization). Perhaps you could have a `Plugins` property of type `IEnumerable<IPlugin>`, where `IPlugin` has a `string PropertyName { get; }` and `object Value { get; }`, and then some sort of custom serialization which transforms that into the correct JSON? Then supporting a plugin is as simple as implementing `IPlugin`.

**Comment by djcarter85** [comment]
The problem with this approach is that you'd have to carefully work out where to add the new `Plugins` property. Maybe you could have a base class that all chart classes inherit from, so that any class can have a plugin?

**Comment by mattosaurus** [comment]
This might work and would be a good way to make the whole project more flexible, I'll have a look at implementing it over the weekend and see if it's practical.

**Comment by mattosaurus** [comment]
After a while trying to figure this out I discovered that this is already catered for by the Newtonsoft serializer, I've added a PluginDynamic property to all objects which you can use for this and have updated the readme.
