### ISSUE TITLE
Padding can have top/right/bottom/left values

### ISSUE THREAD

**Issue by djcarter85** [mattosaurus/ChartJSCore#20]
In Chart.js, `chart.options.layout.padding` can have 4 values rather than just the one that ChartJSCore supports. Can a new class be added?

**Comment by mattosaurus** [comment]
I've added a [PaddingObject](https://github.com/mattosaurus/ChartJSCore/blob/master/src/ChartJSCore/Models/Layout/Layout.cs) property to the layout method. As Padding can be either an integer or an object I want to support both and it's either this or make it an object which feels dirtier. If you think this is the best solution let me know and I'll update the NuGet package.

**Comment by djcarter85** [comment]
Seems like a good solution to me!
Would be interested to know what happens if you populate both. I imagine the JSON serialization will fail?

**Comment by mattosaurus** [comment]
Yep, the JSON serializer throws an error, I'd say this is probably the correct behavior in these circumstances.
