### ISSUE TITLE
LegendLabel Properties

### ISSUE THREAD

**Issue by felrya** [mattosaurus/ChartJSCore#23]
In the LegendLabel class, the FontColor, FontFamily and FontStyle properties should be string types.  Currently all of the properties in this class are int? types.

I am trying to set the FontColor to white, but any integer that I put for it, the font color is set to black.  I was able to make a class that derives from LegendLabel and hide the FontColor property with a FontColor property of type string so I can set the value to "#fff" and this works.

**Comment by mattosaurus** [comment]
Thanks for pointing this out, I've updated the code and pushed out v1.3.1 of the package to NuGet.
