### ISSUE TITLE
Chart Title Does Not Support String[]

### ISSUE THREAD

**Issue by ghost** [mattosaurus/ChartJSCore#24]
`public class Title : Base
    {
       public string Text { get; set; }
    }`

ChartJs supports setting the Title as an array of strings for the purpose of enabling a multi-line chart title. I would like to see the same supported with ChartJSCore.

**Comment by mattosaurus** [comment]
Hi @budoray, yes, the datatype of the text field in chart.js can either accept a string or string[] datatype. I think I decided to set this as a string in this project as I figured that was going to simplest and most used option. I'm wary of changing the datatype of this field as that would be a breaking change. One option you can use to set this to an array is the new(ish) PluginDynamic field I added to the base type which can override the text value provided it's not initialized.

`            options.Title = new Title()
            {
                PluginDynamic = new Dictionary<string, object> { { "text", new List<string>() { "First Line", "Second Line" } } }
            };`

I appreciate that it's not the most elegant option but hopefully it'll work for you.

**Comment by ghost** [comment]
Nice.  I prefer readable over elegance any day. Worked as you suggested. (Second Chart Image)

`//Title = new Title { Text = $"Calls Per Hour EXT 1104", Display = true, FontSize = 22 },
Title = new Title()
{
    PluginDynamic = new Dictionary<string, object>
    {
        {
            "text", new List<string>()
            {
                "Calls Per Hour", "EXT 1104"
            }
         }
     },
     Display = true,
     FontSize = 22
},
`
![image](https://user-images.githubusercontent.com/4522689/45891274-2a296c00-bd93-11e8-9b0b-e76b3e67f586.png)

**Comment by ghost** [comment]
Using PluginDynamic works as expected.
