### ISSUE TITLE
ChartJSCore Zoom

### ISSUE THREAD

**Issue by couperyork** [mattosaurus/ChartJSCore#3]
Hi there, more of a suggestion but would it be possible or how difficult would it be to add/implement the https://github.com/chartjs/chartjs-plugin-zoom zoom plugin to extend your chartsjs wrapper? 

On another note, I enjoy this .NET charts JS library and use it often, works great. Cheers!

**Comment by mattosaurus** [comment]
Hi @couper321, glad the package is proving useful for you :)

Theoretically I don't think it should be that difficult so am happy to add this in for you. The only problem is there doesn't seem to be a nice list of all the available options for this plugin as there is for the standard Chart.js one.

If you're able to put together something like the documentation [here](http://www.chartjs.org/docs/latest/configuration/tooltip.html) (or point me towards a pre-existing version) then I'll base the code off of that.

**Comment by couperyork** [comment]
Sweet! From what I can gather and do at a guess of the initial basic options .... Room for improvement as like you say there isn't much option documentation at this stage.

#### To configure the zoom and pan plugin, you can simply add new config options to your chart config.

## Container for pan options
| Name | Type | Default | Description |
:------------ | :------------- | :------------- | :-------------
`enabled` | `boolean` | `true` | Boolean to enable panning
`mode` | `string` | `xy` | Panning directions. Remove the appropriate direction to disable Eg. 'y' would only allow panning in the y direction
`rangeMin` | `{ x: float,  y: float }` |  no default? | Format the min pin range depending on scale type
`rangeMax` | `{ x: float y: float }` | no default? | Format the max pin range depending on scale type 
 
## Container for zoom options
| Name | Type | Default | Description |
------------ | ------------- | ------------- | -------------
`enabled` | `boolean` | `true` | Boolean to enable zooming
`drag` | `boolean` | `true` | Enable drag-to-zoom behavior
`mode` | `string` | `xy` | Panning directions. Remove the appropriate direction to disable Eg. 'y' would only allow panning in the y direction
`rangeMin` | `{ x: float,  y: float }` | no default? | Format the min pin range depending on scale type
`rangeMax` | `{ x: float y: float }` | no default? | Format the max pin range depending on scale type  

I noticed there are a few extra default options in the actual chartsjs-zoom.js src such as `sensitivity` of `3` , for pan options and zoom options of `speed` of `20` and `threshold` of `10` https://github.com/chartjs/chartjs-plugin-zoom/blob/master/src/chart.zoom.js line 22 - 32 etc But not sure entirely what role they play.

Hope this is some help to you and is what you wanted or at least gives a starting point to be extended. I'll be definitely editing this as I find out more.

**Comment by mattosaurus** [comment]
Yeah, I was planning to base it off of the example on the readme page but looking into the code threw up some extra options such as sensitivity which you also found. I'll add in all those mentioned above, I'm assuming that if you don't know about some of the other options then they're not ones you need but would be good to update all possible options at once so I don't need to add the rest in later.

I'll hopefully get time to update this later today.

**Comment by mattosaurus** [comment]
I've added these options in now [https://github.com/mattosaurus/ChartJSCore/tree/master/src/ChartJSCore/Plugins/Zoom](https://github.com/mattosaurus/ChartJSCore/tree/master/src/ChartJSCore/Plugins/Zoom), let me know if you think I've missed anything and if you're happy I'll build and publish an updated NuGet package.

Options can be created like so.

`Options options = new ChartJSCore.Plugins.Zoom.ZoomOptions();`

**Comment by couperyork** [comment]
Looks good from what I can see! 

In terms of installation, do the nuget package and just install the chartsjs-zoom plugin js source like we did for actual chartsJS, (loads afterwards) and away we go :) ?

**Comment by mattosaurus** [comment]
I've built and uploaded the package now. Turns out I needed to add options for the various type charts as well but that's done now.

Let me know if you have any issues with it.
