### ISSUE TITLE
 Problem in Animation.cs

### ISSUE THREAD

**Issue by anderjoy** [mattosaurus/ChartJSCore#30]
Hello...

I found an inconsistency in the events "OnComplete" and "OnProgress", both are like "int?" and the correct one would be "string" with annotation [JsonConverter (typeof (PlainJsonStringConverter))]

**Thanks, this framework saved my day.**

**Comment by mattosaurus** [comment]
Glad you're finding it useful :)

Good spot on the types in animation, I've updated these now and have pushed out v1.4.2.
