### ISSUE TITLE
Error custom GridLines for x axis or/and y axis

### ISSUE THREAD

**Issue by Bakuryuuha** [mattosaurus/ChartJSCore#31]
i found something wrong with the model in Option > CartesianScale > GridLines because it`s List<GridLines> althought in ChartJs it`s only GridLines, it`s caused my Chart can`t be customized through GridLines model like thicker x axis or/and y axis, it`s only show no lines at all, https://www.chartjs.org/docs/latest/axes/styling.html#grid-line-configuration

because i need to bold my borderLines for some reason.

thanks

**Comment by mattosaurus** [comment]
Goof spot, I've updated this now as well as adding in a few new properties for GridLine.

I've updated the code and NuGet to v1.4.3
