### ISSUE TITLE
Question regarding ChartColor

### ISSUE THREAD

**Issue by mmtabak** [mattosaurus/ChartJSCore#37]
Hi,
I'm quite new to ChartJS and found your library on Github.

I was able to create a barchart with data from my database. However, I'm struggling with the backgroundcolors. I used the following line of code to set the backgroundcolor:
ChartColor.FromRgba(255,99, 132, 0.2)

However, the result shows a black chart. I inspected the source page in my browser and I saw that the corresponding line is executed to:
ChartColor.FromRgba(255,99, 132, 0,2)

(so, with a comma instead of a dot for the decimal separator).

This has probably to do with my regional settings, following the Dutch settings, with a comma for the decimal separator.

Probably I'm making some mistake somewhere, but I was not able to find where. Do you have any idea?

Thanks in advance for your response.

**Comment by mattosaurus** [comment]
Looks like this was down to the color ToString method returning the alpha value in the local culture, I've changed this to InvariantCulture and now it always outputs with a period rather than a comma. I've pushed out a v1.5.1 of the NuGet package.
