### ISSUE TITLE
Where is the BarOptions for bar chart?

### ISSUE THREAD

**Issue by abdllhcay** [mattosaurus/ChartJSCore#42]
Any type of chart has Options class except bar chart. BarOptions used in demo page but can't find in current version. How can I set options for bar chart?

**Comment by mattosaurus** [comment]
Hi, BarOptions was moved to the scale as per #40 as the settings weren't being picked up as part of the options object. There's an example of this in the test [here](https://github.com/mattosaurus/ChartJSCore/blob/master/src/ChartJSCoreTest/BarChartTests.cs) and I'll also update the demo site code.
