### ISSUE TITLE
Using PlainJsonStringConverter on PluginDynamic property

### ISSUE THREAD

**Issue by neutromancer** [mattosaurus/ChartJSCore#44]
I'm trying to add a callback to a plugin option for datalabels, it works but it serializes it in quotes. I know there's a PlainJsonStringConverter but I have no idea how to make it work with a dynamic dictionary such as PluginDynamic. This is my code:

`PluginDynamic = new Dictionary<string, object>
{
    {
        "plugins", new Dictionary<string, object>
        {
            {
                "datalabels", new Dictionary<string, object>
                {
                    {
                        "formatter",  "function(value, context) { return context.dataIndex + ': ' + Math.round(value*100) + '%' }"
                    }
                }
            }
        }
    }
}`

**Comment by neutromancer** [comment]
I ended up creating a DataLabels class with the attribute, but I still would like to know if it's possible to do without a strong typed class.

**Comment by mattosaurus** [comment]
PlainJsonStringConverter can be used to decorate a string attribute.

So if you have the following DataLabels model.

```
public class DataLabels
{
	[JsonConverter(typeof(PlainJsonStringConverter))]
	public string Formatter { get; set; }

	public ChartColor Color { get; set; }
}
```

You can add it to the PluginDynamic dictionary

```
DataLabels dataLabels = new DataLabels()
{
	Color = ChartColor.FromHexString("#36A2EB"),
	Formatter = "function(value, context) { return context.dataIndex + ': ' + Math.round(value*100) + '%' }"
};

options.PluginDynamic = new Dictionary<string, object>() { { "plugins", dataLabels } };
```

And the specified function will be returned without quotes.

**Comment by aniljavali** [comment]
Hello,

I want to add label to the top of the bar. Found this JavaScript (http://jsfiddle.net/uh9vw0ao/).
How can achieve this using c#.

```
var ctx = document.getElementById("myChart2").getContext("2d");
var myBar = new Chart(ctx).Bar(chartData, {
    showTooltips: false,
    onAnimationComplete: function () {

        var ctx = this.chart.ctx;
        ctx.font = this.scale.font;
        ctx.fillStyle = this.scale.textColor
        ctx.textAlign = "center";
        ctx.textBaseline = "bottom";

        this.datasets.forEach(function (dataset) {
            dataset.bars.forEach(function (bar) {
                ctx.fillText(bar.value, bar.x, bar.y - 5);
            });
        })
    }
});
```

**Comment by mattosaurus** [comment]
Hi @aniljavali, check out the [Bar chart example](https://github.com/mattosaurus/ChartJSCore/blob/master/src/ChartJSCoreTest/BarChartTests.cs) and modify it accordingly.

**Comment by aniljavali** [comment]
Yes, I am able to generate Bar Chart using c#. But, I want to attach onAnimationComplete event to execute following method that will add bar.value to the top of each bar in the chart.
```

onAnimationComplete: function () {

        var ctx = this.chart.ctx;
        ctx.font = this.scale.font;
        ctx.fillStyle = this.scale.textColor
        ctx.textAlign = "center";
        ctx.textBaseline = "bottom";

        this.datasets.forEach(function (dataset) {
            dataset.bars.forEach(function (bar) {
                ctx.fillText(bar.value, bar.x, bar.y - 5);
            });
        })
    }
```

**Comment by mattosaurus** [comment]
You should be able to use the [animation object](https://github.com/mattosaurus/ChartJSCore/blob/master/src/ChartJSCore/Models/Options/Animation/Animation.cs) which is a property of the options object. Set the OnComplete property of this to a string containing your function.

**Comment by aniljavali** [comment]
below onAnimationComplete function works expected with Chart.js v1.0.2 but not with v2.8.0. Any thoughts?

`

onAnimationComplete: function () {

        var ctx = this.chart.ctx;
        ctx.font = this.scale.font;
        ctx.fillStyle = this.scale.textColor
        ctx.textAlign = "center";
        ctx.textBaseline = "bottom";

        this.datasets.forEach(function (dataset) {
            dataset.bars.forEach(function (bar) {
                ctx.fillText(bar.value, bar.x, bar.y - 5);
            });
        })
    }
`
