### ISSUE TITLE
How to create a horizontal floating bar graph with time on the X Scale?

### ISSUE THREAD

**Issue by chdorow** [mattosaurus/ChartJSCore#49]
I have a .NET Core project using Razor Pages.  I can successfully create a horizontal bar graph, but with data points that are doubles - not time.  I can't seem to find a good example on how to do this in C# using this project.  From what I can tell, the data portion in your BarDataset class is limited to a list of doubles.  It seems ChartJS wants a time format instead or am I missing something?  ChartJS also allows for floating bars by specifying a start and end.  Is this possible using ChartJSCore?

**Comment by mattosaurus** [comment]
Currently data points in the Dataset object can only be doubles, potentially this could be changed to an object to allow other data types.

Are you able to create an object that inherits from Dataset and overrides the Data property and use that? That might be the easiest option, something like this maybe.

```
public class MyDataset : Dataset
{
	public new IList<Tuple<int, int>> Data { get; set; }
}
```
