### ISSUE TITLE
Tooltip Callbacks

### ISSUE THREAD

**Issue by barrettg** [mattosaurus/ChartJSCore#5]
I'm trying to format my tooltips as currency using the same methodology as the Tick callback on Scales.  I am not able to produce an uncommented string and therefor Javascript is throwing an error.  Do you have an example of implementing a tooltip callback?  Thanks!

**Comment by mattosaurus** [comment]
Hi @barrettg, I've updated the Custom value of Tooltip to output raw json as I assume this was what you're referring to. This should work the same as the Tick Callback property now, let me know if not.

**Comment by mattosaurus** [comment]
Actually, thinking about this, the Callback properties under Tooltip should also output raw JSON, have updated and published as 1.1.4 now.
