### ISSUE TITLE
Radar Chart - Start at 0 and end at 100, increments of 10

### ISSUE THREAD

**Issue by Skeldave** [mattosaurus/ChartJSCore#50]
Hi,

I have implemented a radar chart and it all works well except that I can't get the values to start at 0 and end at 100 and also increment in 10. According to other chartjs posts this is possible.

The following structure is needed

`scale: {
      ticks: {
        beginAtZero: true,
        max: 5,
        min: 0,
        stepSize: 1
    }
}`

I can only see how to apply ticks to X and Y axis and not at the top level.

Thanks,

**Comment by mattosaurus** [comment]
Looks like I was missing this option, have added it in now and published v1.5.6 to NuGet.

```
chart.Options = new RadarOptions()
{
	Scale = new RadialScale()
	{
		Ticks = new RadialLinearTick()
		{
			BeginAtZero = true,
			Max = 5,
			Min = 0,
			StepSize = 1
		}
	}
};
```
