### ISSUE TITLE
Deprecated Options

### ISSUE THREAD

**Issue by Skeldave** [mattosaurus/ChartJSCore#51]
Hi,

Some of the options that ChartJSCore generates are deprecated. 

Below are the ones I've come across but there may be others.

> bar chart: "scales.[x/y]Axes.barPercentage" is deprecated. Please use "dataset.barPercentage" instead

> bar chart: "scales.[x/y]Axes.maxBarThickness" is deprecated. Please use "dataset.maxBarThickness" instead

> bar chart: "scales.[x/y]Axes.barThickness" is deprecated. Please use "dataset.barThickness" instead

I'm using chart.js 2.9.3

There is no rush to update these but it would be good to update going forward. 

Thanks

**Comment by mattosaurus** [comment]
Good point, I'll go through and align this with the current version of Chart.js when I get a chance, it seems to have changed quite a bit since I originally created this package.

**Comment by mattosaurus** [comment]
I'm going to assume this is fixed with the new v3 release, please re-open and provide example code if that's not actually the case.
