### ISSUE TITLE
Add Support to null values in dataset data.

### ISSUE THREAD

**Issue by Fandradec** [mattosaurus/ChartJSCore#55]
When you want to show a series of data where one of the values ​​does not exist, or there is no data, you should be able to add "null" instead of 0.
For that, the Dataset class is modified, its Data property from List <double> to List <double?>

https://jsfiddle.net/fjfandradec/pfnvj3q4/

**Comment by mattosaurus** [comment]
Thanks, I didn't realise null data points were acceptable, I've accepted your PR and published v1.5.7 to NuGet.
