### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by DavidStania** [mattosaurus/ChartJSCore#57]
![image](https://user-images.githubusercontent.com/27513913/75146852-3fc76180-56fc-11ea-9f2e-28fc424ecacd.png)

Small problem detected in your example code by passing list of double. Type should be nullable "double?".
`Data = new List<double?> { 65, 59, 80, 81, 56, 55, 40 },`

Best regards.

**Comment by mattosaurus** [comment]
Thanks, forgot about the sample code in the readme when I changed this, I've updated it now.
