### ISSUE TITLE
Howto use {x: val_X, y: val_Y} format for data?

### ISSUE THREAD

**Issue by bairog** [mattosaurus/ChartJSCore#58]
Hello.
According to [this](https://github.com/chartjs/Chart.js/issues/4096#issuecomment-434943049) the only way to use `horizontalBar` chart mixed with `line` 
is to use `{x: val_X, y: val_Y}` format for data.
Howto use it with ChartJSCore?

**Comment by mattosaurus** [comment]
Hi, unfortunatly this isn't possible with ChartJSCore as at the moment, the `Data` object just accepts an `IList<double?>`. This doesn't seem to be offically supported in chart.js either with the method provided being a workaround, I don't really want to change this to `IList<object?>` as that feels a bit too open but I'll have a think if there's a better way of doing it.

Feel free to submit a PR if you can think of a more elegant way of doing it or alternatly you could just clone the project and update it to `IList<object?>` in your local version.
