### ISSUE TITLE
How to add two diferent objects into YAxes (Scale) list?

### ISSUE THREAD

**Issue by Marlohn** [mattosaurus/ChartJSCore#61]
Im trying to add two diferent objects into YAxes (Scale) list but it appears dont works.

If I try to add just any one separated it works fine!

                YAxes = new List<Scale>{
                    new BarScale
                    {
                        GridLines = new GridLine()
                        {
                            Display = false,
                            DrawBorder = false
                        }

                    },
                    new CartesianScale
                    {
                        Ticks = new CartesianLinearTick
                        {
                            Display = false
                        }
                    }
                }

I think this is a problem with Newtonsoft.Json that cant serialize diferent types of objects in a Inheritance list

**Comment by mattosaurus** [comment]
Hi, yeah, I think this is a serialization issue. I'm not really sure how we'd get around this, any ideas?
