### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by mayureshs** [mattosaurus/ChartJSCore#62]
Is there any way I can export the chart object into a PDF as an image ?

**Comment by mattosaurus** [comment]
Hi, not directly using this library but there are libraries such as PDFsharp that you can use to render HTML and export that to a PDF so you might be able to use that.

**Comment by mayureshs** [comment]
Thanks for the response. Is there anyway I can create graph and add it to pdf server side without rendering HTML.

**Comment by mattosaurus** [comment]
No, sorry. All this library does is generate the javascript required for the chart.js plugin to actually render the graph, the rendering is all done in the browser by chart.js.

**Comment by mayureshs** [comment]
Thank you. Closing the issue, if possible do consider it as a feature request.
