### ISSUE TITLE
LineDataSet "Fill"

### ISSUE THREAD

**Issue by aherrick** [mattosaurus/ChartJSCore#64]
Why is the LineDataSet Fill property a string not a bool?

```
/// <summary>
        /// If true, fill the area under the line.
        /// </summary>
        [JsonConverter(typeof(BoolIntStringConverter))]
        public string Fill { get; set; }
```

**Comment by mattosaurus** [comment]
Fill can be either a bool, int or string according to the documentation.

https://www.chartjs.org/docs/latest/charts/area.html#filling-modes
