### ISSUE TITLE
Axes changed in v3.5

### ISSUE THREAD

**Issue by dyeazel** [mattosaurus/ChartJSCore#68]
The x and y axes have changed in Chart.js v3.0. Previously they were arrays xAxes and yAxes. They are now X and Y.
https://www.chartjs.org/docs/next/getting-started/v3-migration.html .

**Comment by mattosaurus** [comment]
Yeah, I think I need to refactor quite a few of the models to work with v3. I started on this recently but then got distracted by other projects. I'll see if I can pick this up again in the next week or two.

**Comment by AgostinoArcasensa** [comment]
Any info about this issue? It would be really useful to be supported by your nuget in the use of chart.js 3.X

**Comment by mattosaurus** [comment]
I made a start on it but then got sidetracked. I'm hoping to finish it off this week or next.

**Comment by AgostinoArcasensa** [comment]
After the update your library works again like a charm. Thanks!

**Comment by mattosaurus** [comment]
Happy to hear this is now working for you. please let me know if you hit any bugs.
