### ISSUE TITLE
Line chart fill with multiple colors

### ISSUE THREAD

**Issue by bcanteneurEiffage** [mattosaurus/ChartJSCore#70]
Is it possible to fill the line charts (making them area charts) with multiple colors for above and below as described in the documentation of Chartjs?
https://www.chartjs.org/docs/latest/charts/area.html#example-with-multiple-colors

**Comment by mattosaurus** [comment]
I'm going to assume this is fixed with the new v3 release, please re-open and provide example code if that's not actually the case.
