### ISSUE TITLE
Line chart Stepped not working

### ISSUE THREAD

**Issue by bcanteneurEiffage** [mattosaurus/ChartJSCore#71]
C# properties is called SteppedLine but json properties should be stepped according to the documentation https://www.chartjs.org/docs/latest/charts/line.html#stepped

The issued chart is not good :
`{"type":"line","data":{"datasets":[{"type":"line","fill":false,"lineTension":0.0,"backgroundColor":"rgba(0, 0, 0, 0.3)","borderColor":"rgba(0, 0, 0, 1)","borderCapStyle":"butt","borderDash":[],"borderDashOffset":0.0,"borderJoinStyle":"miter","pointBorderColor":"rgba(0, 0, 0, 1)","pointBackgroundColor":"rgba(0, 0, 0, 1)","pointBorderWidth":1,"pointRadius":4,"pointHoverRadius":4,"pointHitRadius":10,"pointHoverBackgroundColor":"rgba(255, 255, 255, 1)","pointHoverBorderColor":"rgba(0, 0, 0, 1)","pointHoverBorderWidth":2,"spanGaps":true,"steppedLine":true,"data":[6.0,null,6.0,5.0],"label":"Goal Values"}],"labels":["01/11/2021","15/11/2021","01/12/2021","01/01/2022"]},"options":{}}`

**Comment by mattosaurus** [comment]
I'm going to assume this is fixed with the new v3 release, please re-open and provide example code if that's not actually the case.
