### ISSUE TITLE
Bug in JSON with Title model 

### ISSUE THREAD

**Issue by jfcontart** [mattosaurus/ChartJSCore#74]
hello,
I found a bug with title and I solved it

I just tried 
`
chart.Options.Plugins = new Plugins
            {
                Title = new Title()
                {
                    Display = true,
                    Text = "Burndown Chart",
                }
            };
`
 result => exec bad ... app crash

I resolved it with this trick

in Title.cs 
line 47 ... remove [JsonConverter(typeof(SingleOrArrayConverter<string>))] 
string must be linearize as string

Can you confirm? 

thank you

**Comment by mattosaurus** [comment]
Hi, thanks for spotting that.

Looks like title can either be a string or an array of strings so I've updated `Text` to be an `IList<string>`.

You can use it like so.

`chart.Options.Plugins = new Plugins { Title = new Title() { Display = true, Text = new List<string>() { "Burndown Chart" } } };`

**Comment by jfcontart** [comment]
Hi,
tested! it fixed the issue!
thank you! :-)
