### ISSUE TITLE
Plugins does not have a PluginDynamic member

### ISSUE THREAD

**Issue by OriginalArkus** [mattosaurus/ChartJSCore#75]
Many plugins for chart.js require configuration defined under the `options > plugins` section of configuration. For example, see https://emn178.github.io/chartjs-plugin-labels/samples/demo/

Sadly, the Plugins class does not contain a PluginDynamic member, so custom data cannot be added at this level of configuration.

**Comment by mattosaurus** [comment]
Fixed thanks to your PR #76
