### ISSUE TITLE
How to change chart type from front end

### ISSUE THREAD

**Issue by fasteddys** [mattosaurus/ChartJSCore#82]
Hello this is great, I see many widget that allow the user to switch between a bar graph to a column etc from the front end in a dashboard.

Can you please share some guidance or a sample from and ASP MVC Core 6 view

**Comment by mattosaurus** [comment]
Hi, you can update the data in a chart and refresh the chart but you can't change the type of chart.

You're best bet is probably to render multiple canvases and hide the ones you're not using and to use a dropdown to unhide the selected canvas.

**Comment by fasteddys** [comment]
Hello @mattosaurus thanks for the response, here is sample code to post back the change in chart type

https://jsfiddle.net/canvasjs/yzewncsh/ - can we incorporate this or this https://stackoverflow.com/q/25443627/6085193

**Comment by mattosaurus** [comment]
You should be able to do the one linked in the jsfiddle. ChartJSCore just outputs javascript to your HTML view so you could add in more javascript there to hook into it and rerender when a dropdown is changed.

**Comment by fasteddys** [comment]
thanks, since some of this is configured/ set rendered in the backend, what action would I trigger, or post to so that it can rewrap and get that served back to the client.

Or would I not need to go back to the server?
