### ISSUE TITLE
Contribute to ChartJSCore

### ISSUE THREAD

**Issue by ghost** [mattosaurus/ChartJSCore#9]
Hi mattosaurus
I like what you have done with ChartJSCore. I have forked your project but think maybe I should rather contribute directly to your code.

For a start I would like to add Appveyor continues build integration and add badgets to your readme file.
See: https://github.com/perezLamed/LamedalCore (for sample of my project)

I have created following project to extent functionality of ChartJSCore.
https://github.com/perezLamed/LamedalCore_ChartJS/

Would be great to hear your thoughts.

Regards Perez Lamed

**Comment by mattosaurus** [comment]
Hi @perezLamed, I'd be happy for you to contribute to this project so if you've got any suggested changes please submit them.

Regarding AppVeyor, I don't have access to this through work and wouldn't want to pay for it myself so would rather not include it in the project.

Matt

**Comment by ghost** [comment]
Hi @mattosaurus 

Thanks for the positive reply. I have submitted 2 pull requests:
1) Added a Nuget badge & version number to readme
2) Add appveyor config file and badge. 

See [AppVeyor](https://www.appveyor.com/pricing/). It is free for open source projects. You can use your github account. It really helps with quality check of pull requests.

Please review and give feedback. See my [Fork](https://github.com/perezLamed/ChartJSCore/) for final result.

Regards
