### ISSUE TITLE
Can I get the sample that works on Blazor?

### ISSUE THREAD

**Issue by 1Sam** [mattosaurus/ChartJSCore#94]
I can not control the section Scripts in Blazor.
It is hard for me to convert your same to Blazor page.

**Comment by mattosaurus** [comment]
Hi, sorry I haven't used Blazor for a long time so I don't think I'll be able to create a working example.

**Comment by samuelo269** [comment]
Hello, 
@mattosaurus can I take over this issue and create a Blazor app with demo page including all of the charts ?

**Comment by mattosaurus** [comment]
Hi, of course. Always happy for someone to help out :)

**Comment by samuelo269** [comment]
I have submitted a fix for this issue in #100

**Comment by mattosaurus** [comment]
Apologies, I'm in holiday at the moment and I'll take a look at this next week.

Thanks for submitting the PR :)
